---

driver:
  name: docker

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: centos
    driver_config:
      image: centos:6
      use_cache: true
  - name: ubuntu
    driver_config:
      image: ubuntu:14.04
      use_cache: true
    run_list:
      - recipe[apt]
